ALTER TABLE patient_data ADD COLUMN ad_reviewed date DEFAULT NULL;
ALTER TABLE patient_data ADD COLUMN allow_patient_portal varchar(31) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN billing_note text;
ALTER TABLE patient_data ADD COLUMN birth_fname text;
ALTER TABLE patient_data ADD COLUMN birth_lname text;
ALTER TABLE patient_data ADD COLUMN birth_mname text;
ALTER TABLE patient_data ADD COLUMN care_team_facility text;
ALTER TABLE patient_data ADD COLUMN care_team_provider text;
ALTER TABLE patient_data ADD COLUMN care_team_status text;
ALTER TABLE patient_data ADD COLUMN city varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN cmsportal_login varchar(60) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN completed_ad varchar(3) NOT NULL DEFAULT 'NO';
ALTER TABLE patient_data ADD COLUMN contact_relationship varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN contrastart date DEFAULT NULL COMMENT 'Date contraceptives initially used';
ALTER TABLE patient_data ADD COLUMN country_code varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN county varchar(40) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN created_by bigint DEFAULT NULL COMMENT 'users.id the user that first created this record';
ALTER TABLE patient_data ADD COLUMN date datetime DEFAULT NULL;
ALTER TABLE patient_data ADD COLUMN deceased_date datetime DEFAULT NULL;
ALTER TABLE patient_data ADD COLUMN deceased_reason varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN DOB date DEFAULT NULL;
ALTER TABLE patient_data ADD COLUMN drivers_license varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN dupscore int NOT NULL DEFAULT '-9';
ALTER TABLE patient_data ADD COLUMN email varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN email_direct varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN ethnicity varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN ethnoracial varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN family_size varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN financial varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN financial_review datetime DEFAULT NULL;
ALTER TABLE patient_data ADD COLUMN fitness int NOT NULL DEFAULT '0';
ALTER TABLE patient_data ADD COLUMN fname varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN gender_identity text;
ALTER TABLE patient_data ADD COLUMN genericname1 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN genericname2 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN genericval1 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN genericval2 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN hipaa_allowemail varchar(3) NOT NULL DEFAULT 'NO';
ALTER TABLE patient_data ADD COLUMN hipaa_allowsms varchar(3) NOT NULL DEFAULT 'NO';
ALTER TABLE patient_data ADD COLUMN homeless varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN id bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE patient_data ADD COLUMN interpretter varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN language varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN lname varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN migrantseasonal varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN mname varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN monthly_income varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN mothersname varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN name_history tinytext;
ALTER TABLE patient_data ADD COLUMN patient_groups text;
ALTER TABLE patient_data ADD COLUMN phone_biz varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN phone_cell varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN phone_contact varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN phone_home varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN pid bigint NOT NULL DEFAULT '0';
ALTER TABLE patient_data ADD COLUMN postal_code varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN pricelevel varchar(255) NOT NULL DEFAULT 'standard';
ALTER TABLE patient_data ADD COLUMN providerID int DEFAULT NULL;
ALTER TABLE patient_data ADD COLUMN pubpid varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN race varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN referral_source varchar(30) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN referrer varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN referrerID varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN regdate datetime DEFAULT NULL COMMENT 'Registration Date';
ALTER TABLE patient_data ADD COLUMN religion varchar(40) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN sex varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN sexual_orientation text;
ALTER TABLE patient_data ADD COLUMN soap_import_status tinyint DEFAULT NULL COMMENT '1-Prescription Press 2-Prescription Import 3-Allergy Press 4-Allergy Import';
ALTER TABLE patient_data ADD COLUMN squad varchar(32) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN ss varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN state varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN status varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN street varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN street_line_2 tinytext;
ALTER TABLE patient_data ADD COLUMN suffix tinytext;
ALTER TABLE patient_data ADD COLUMN title varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN updated_by bigint DEFAULT NULL COMMENT 'users.id the user that last modified this record';
ALTER TABLE patient_data ADD COLUMN userlist1 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN userlist2 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN userlist3 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN userlist4 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN userlist5 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN userlist6 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN userlist7 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN usertext1 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN usertext2 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN usertext3 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN usertext4 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN usertext5 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN usertext6 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN usertext7 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN usertext8 varchar(255) NOT NULL DEFAULT '';
ALTER TABLE patient_data ADD COLUMN uuid binary(16) DEFAULT NULL;
ALTER TABLE patient_data ADD COLUMN vfc varchar(255) NOT NULL DEFAULT '';